### ISSUE TITLE
Slice Sampling for LDA's Hyperparameter

### ISSUE THREAD

**Issue by hongliangjie** [kzhai/PyLDA#5]
In LDA's slice sampling code:

Line 118: r_log_alpha_alpha = old_log_alpha_alpha + hyper_parameter_step;

Should it be:
r_log_alpha_alpha = l_log_alpha_beta + hyper_parameter_step?

(Similar issue with beta as well)

On http://projecteuclid.org/download/pdf_1/euclid.aos/1056562461's page 715:

L = x0 - w \* U
R = L + w

**Comment by kzhai** [comment]
Got it, just fix the bug. Thanks.
