### ISSUE TITLE
iteration of phi

### ISSUE THREAD

**Issue by kaiyinzhou** [kzhai/PyLDA#7]
Hi @kzhai ,
it's a nice work. 
when i am reading you code , i find that the iteration of phi is a little different from the iteration formular:
![图片](https://user-images.githubusercontent.com/33114591/59811819-20db2900-933e-11e9-94c3-e6b5969fbae6.png)
where is a "lambda" rather then a "eta" in you code,
```log_phi = E_log_eta[:, term_ids].T + numpy.tile(scipy.special.psi(gamma_values[[doc_id], :]), (word_ids[doc_id].shape[0], 1));```

**Comment by kaiyinzhou** [comment]
The above iteration formular is deductived from smoothed LDA model. Here your model does not  seem to introduce variational parameters lambda.

**Comment by kzhai** [comment]
they are the same, where `lambda` is a reserved keyword in python and might introduce some unnecessary problem in the code
